"""add_my_services_models

Revision ID: 3e2304a3b079
Revises: b2c3d4e5f6g7
Create Date: 2026-09-17 14:53:28.409128
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3e2304a3b079'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('late_fee_policies',
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('daily_rate_percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id')
    )
    op.create_index('ix_late_fee_policies_building_id', 'late_fee_policies', ['building_id'], unique=False)
    op.create_table('service_catalog',
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.Enum('ELECTRICITY', 'WATER', 'MANAGEMENT_FEE', 'PARKING', 'MAINTENANCE', 'OTHER', name='service_type', native_enum=False), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_catalog_building_id', 'service_catalog', ['building_id'], unique=False)
    op.create_table('apartment_services',
    sa.Column('apartment_id', sa.Uuid(), nullable=False),
    sa.Column('service_catalog_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='apartment_service_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_pay_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_catalog_id'], ['service_catalog.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apartment_services_apartment_id', 'apartment_services', ['apartment_id'], unique=False)
    op.create_index('ix_apartment_services_catalog_id', 'apartment_services', ['service_catalog_id'], unique=False)
    op.create_table('manual_confirmations',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='manual_confirmation_status', native_enum=False), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'BANK_TRANSFER', name='manual_payment_method', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manual_confirmations_invoice_id', 'manual_confirmations', ['invoice_id'], unique=False)
    op.create_table('payment_reminders',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('APP', 'SMS', 'ZALO', 'EMAIL', name='reminder_channel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='reminder_status', native_enum=False), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_reminders_invoice_id', 'payment_reminders', ['invoice_id'], unique=False)
    op.alter_column('billing_cycles', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'CALCULATED', 'INVOICED', 'CLOSED', name='billing_cycle_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.add_column('invoice_items', sa.Column('service_catalog_id', sa.Uuid(), nullable=True))
    op.alter_column('invoice_items', 'service_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ELECTRICITY', 'WATER', 'MANAGEMENT_FEE', 'PARKING', 'MAINTENANCE', 'OTHER', name='service_type', native_enum=False),
               existing_nullable=False)
    op.create_foreign_key(None, 'invoice_items', 'service_catalog', ['service_catalog_id'], ['id'], ondelete='SET NULL')
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='invoice_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('payment_methods', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('VNPAY', 'MOMO', 'ZALOPAY', 'STRIPE', name='payment_provider', native_enum=False),
               existing_nullable=False)
    op.alter_column('transactions', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('VNPAY', 'MOMO', 'ZALOPAY', 'STRIPE', name='payment_provider', native_enum=False),
               existing_nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED', name='transaction_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED', name='transaction_status', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('transactions', 'provider',
               existing_type=sa.Enum('VNPAY', 'MOMO', 'ZALOPAY', 'STRIPE', name='payment_provider', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('payment_methods', 'provider',
               existing_type=sa.Enum('VNPAY', 'MOMO', 'ZALOPAY', 'STRIPE', name='payment_provider', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('DRAFT', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='invoice_status', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.alter_column('invoice_items', 'service_type',
               existing_type=sa.Enum('ELECTRICITY', 'WATER', 'MANAGEMENT_FEE', 'PARKING', 'MAINTENANCE', 'OTHER', name='service_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('invoice_items', 'service_catalog_id')
    op.alter_column('billing_cycles', 'status',
               existing_type=sa.Enum('OPEN', 'CALCULATED', 'INVOICED', 'CLOSED', name='billing_cycle_status', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_index('ix_payment_reminders_invoice_id', table_name='payment_reminders')
    op.drop_table('payment_reminders')
    op.drop_index('ix_manual_confirmations_invoice_id', table_name='manual_confirmations')
    op.drop_table('manual_confirmations')
    op.drop_index('ix_apartment_services_catalog_id', table_name='apartment_services')
    op.drop_index('ix_apartment_services_apartment_id', table_name='apartment_services')
    op.drop_table('apartment_services')
    op.drop_index('ix_service_catalog_building_id', table_name='service_catalog')
    op.drop_table('service_catalog')
    op.drop_index('ix_late_fee_policies_building_id', table_name='late_fee_policies')
    op.drop_table('late_fee_policies')
    # ### end Alembic commands ###
